### ISSUE TITLE
Error: Cannot find module 'tslib'

### ISSUE THREAD

**Issue by YujiYashima** [rocketseat-content/youtube-codedrops-adminbro#2]
Eu segui tudo do jeito que o Mayk Brito estava codando, mas estava dando o seguinte erro quando eu rodava o ```node admin.js```:

```
internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module 'tslib'
Require stack:
- D:\Documents\Yuji_Programaçoes\MyProjects\node_modules\@admin-bro\express\lib\buildAuthenticatedRouter.js
- D:\Documents\Yuji_Programaçoes\MyProjects\node_modules\@admin-bro\express\lib\index.js
- D:\Documents\Yuji_Programaçoes\MyProjects\admin.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:864:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1044:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:77:18)←[39m
    at Object.<anonymous> (D:\Documents\Yuji_Programaçoes\MyProjects\node_modules\←[4m@admin-bro←[24m\express\lib\buildAuthenticatedRouter.js:4:17)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1158:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:1002:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:901:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:1044:19)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'D:\\Documents\\Yuji_Programaçoes\\MyProjects\\node_modules\\@admin-bro\\express\\lib\\buildAuthenticatedRouter.js'←[39m,
    ←[32m'D:\\Documents\\Yuji_Programaçoes\\MyProjects\\node_modules\\@admin-bro\\express\\lib\\index.js'←[39m,
    ←[32m'D:\\Documents\\Yuji_Programaçoes\\MyProjects\\admin.js'←[39m
  ]
}
```

Alguem pode me ajudar?? Será que eu errei?? Ou foi erro na biblioteca?? Eu deletei e fiz 3 vezes, mas nao deu certo. Alguem pode me socorrer, por favor??

**Comment by YujiYashima** [comment]
Depois disso, começou a apontar erro na node_modules. O erro está em:

```
node_modules /@admin-bro/express /tsconfig.json
```

**Comment by jpedroschmitz** [comment]
Parece ser um problema recente no AdminBro, dá uma olhada nessa [issue](https://github.com/SoftwareBrothers/admin-bro/issues/772) e vê se resolve 👊🏻
